name: Ubuntu-Server
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa

    - uses: actions/checkout@v2
    - run: source ubuntu-run.sh

    - name: Setup ZSH
      continue-on-error: true
      run: |
        sudo apt install zsh
        sudo chsh -s $(which zsh) runner
        cd /home/runner
        rm .zshrc
        wget https://raw.githubusercontent.com/Batu33TR/Ubuntu-SSH/main/.zshrc
        sudo chmod 755 /usr/share/zsh
        sudo chmod 755 /usr/share/zsh/*
        sudo chmod 755 /usr/share/zsh/*/*
        sudo chmod 755 /usr/share/zsh/*/*/*
 
    - name: Start SSH via ngrok
      continue-on-error: true
      timeout-minutes: 350
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
        NGROK_REGION: eu
        # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
