name: Ubuntu-Server
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa

    - uses: actions/checkout@v2
    - run: source ubuntu-run.sh

    - name: Setup ZSH
      continue-on-error: true
      run: |
        sudo apt install zsh
        sudo chsh -s $(which zsh) runner
        cd /home/runner
        sudo chmod 755 /usr/share/zsh
        sudo chmod 755 /usr/share/zsh/*
        sudo chmod 755 /usr/share/zsh/*/*
        sudo chmod 755 /usr/share/zsh/*/*/*
        cat << EOF > ~/.zshrc
        # Set up the prompt

        autoload -Uz promptinit
        promptinit
        prompt adam1
        
        setopt histignorealldups sharehistory

        # Use emacs keybindings even if our EDITOR is set to vi
        bindkey -e

        # Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
        HISTSIZE=1000
        SAVEHIST=1000
        HISTFILE=~/.zsh_history
        
        # Use modern completion system
        autoload -Uz compinit
        compinit

        zstyle ':completion:*' auto-description 'specify: %d'
        zstyle ':completion:*' completer _expand _complete _correct _approximate
        zstyle ':completion:*' format 'Completing %d'
        zstyle ':completion:*' group-name ''
        zstyle ':completion:*' menu select=2
        eval "$(dircolors -b)"
        zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
        zstyle ':completion:*' list-colors ''
        zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
        zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
        zstyle ':completion:*' menu select=long
        zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
        zstyle ':completion:*' use-compctl false
        zstyle ':completion:*' verbose true

        zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
        zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
        EOF

    - name: Start SSH via ngrok
      continue-on-error: true
      timeout-minutes: 350
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
        NGROK_REGION: eu
        # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
