name: Ubuntu-Server
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa

    - uses: actions/checkout@v2
    - run: source ubuntu-run.sh

    # Some special configs for me :D
    - name: Set GitHub configs
      run: |
        git config --global user.name "Batu33TR"
        git config --global user.email "batuhanarslanoglu4@gmail.com"
        git config --global color.ui true
        git config --global credential.helper store
        echo "https://Batu33TR:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
        git config --global user.signingkey 9C0632EDCCC07A70
        git config --global commit.gpgsign true

    - name: Configure GPG RSA key
      run: |
        brew install gpg gpg2 pinentry
        cd /home/runner
        git clone https://github.com/Batu33TR/gnupg dont_forget_to_import_this
        echo "export GPG_TTY=$(tty)" >> ~/.bash_profile
      # :D

    - name: Start SSH via ngrok
      continue-on-error: true
      timeout-minutes: 350
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
        NGROK_REGION: eu
        # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
